insert into student (student_id, first_name, last_name, email) values ('19010101012', 'Erkinai', 'Shamshidinova', 'erkinai.shamshidinova@iauu.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101010', 'Aida', 'Dosmurat kyzy', 'aida.dosmuratkyzy@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101018', 'Aida', 'Moldalieva', 'aida.moldalieva@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101023', 'Aiperi', 'Askarbek kyzy', 'aiperi.askarbekkyzy@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101038', 'Nursultan', 'Begaliev', 'nursultan.begaliev@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101015', 'Altynai', 'Idirisova', 'altynai.idirisova@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101017', 'Sezim', 'Erali kyzy', 'sezim.eralikyzy@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101001', 'Nataliya', 'Klimareva', 'nataliya.klimareva@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101019', 'Reina', 'Khasanova', 'reina.khasanova@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101011', 'Tilek', 'Karaev', 'tilek.karaev@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101022', 'Dastan', 'Asanov', 'dastan.asanov@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101034', 'Aidar', 'Asakeev', 'aidar.asakeev@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101021', 'Ermek', 'Sagynov', 'ermek.sagynov@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101035', 'Mirkhad', 'Chekirbaev', 'mirkhad.chekirbaev@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101008', 'Tumar', 'Kasmalieva', 'tumar.kasmalieva@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101029', 'Sarvar', 'Saipov', 'sarvar.saipov@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101031', 'Yaseen', 'Mamatov', 'yaseen.mamatov@iaau.edu.kg');
insert into student (student_id, first_name, last_name, email) values ('19010101004', 'Nazik', 'Esenalieva', 'nazik.esenalieva@iaau.edu.kg') ;
insert into student (student_id, first_name, last_name, email) values ('19010101006', 'Zhibek', 'Muktaralieva', 'nazik.muktaralieva@iaau.edu.kg' );
insert into student (student_id, first_name, last_name, email) values ('19010101028', 'Aisuluu', 'Ulanbekkyzy', 'aisuluu.ulanbekkyzy@iaau.edu.kg');
